[tool.poetry]
name = "isha"
version = "0.1.0"
description = ""
authors = ["Hiren Makadia <hiren.makadia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.103.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
